apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deplyment
spec:
  selector:
    matchLabels:
      app: front-angular
  replicas: 1
  template:
    metadata:
      labels:
        app: front-angular
    spec:
      containers:
        - name: angular-front
          image: mohamedns/front:latest
          ports:
            - containerPort: 4200
          
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: frontend-service
spec:
  selector:
    app: front-angular
  ports:
    - protocol: "TCP"
      port: 4200 # The port that the service is running on in the cluster
      targetPort: 4200 # The port exposed by the service
  type: NodePort # type of the service.
